code-423n4/docs

roles/sponsors/contest-process.md

Not sure how to format this. And don't have any more that popped up. 😬

Minor typo

---

README.md

Change to reflect the award calculation.

Fix exponent in shares calc

---

roles/judges/how-to-judge-a-contest.md
roles/wardens/README.md
roles/wardens/judging-criteria.md
roles/wardens/submission-policy.md
structure/where-can-i-find....md

Not sure if this is the goal, but changes (where possible -- when used as domain) code423n4 to code4rena.

Change domain from code423n4 to code4rena

---

roles/wardens/submission-policy.md

Use code423n4.com for e-mail

---

roles/judges/judging-faq.md

Tied to https://github.com/code-423n4/docs/issues/13

Fixing Minor Typo in Judging FAQs

---

roles/wardens/judging-criteria.md

Fixing bullet in Judging Criteria

---

SUMMARY.md
structure/FAQ.md
structure/frequently-asked-questions.md

Add FAQ page to docs

---

roles/judges/how-to-judge-a-contest.md

Update how-to-judge-a-contest.md

JeeberC4-patch-1

---

README.md
SUMMARY.md
awarding/incentive-model-and-awards/README.md
awarding/incentive-model-and-awards/awarding-process.md
awarding/judging-criteria/README.md
roles/certified-contributors/backstage-wardens.md
roles/certified-contributors/lookouts.md
roles/judges/README.md
roles/judges/how-to-judge-a-contest.md
roles/sponsors/README.md
roles/sponsors/contest-process.md
roles/wardens/README.md
roles/wardens/submission-policy.md
roles/wardens/warden-auth.md
structure/frequently-asked-questions.md
structure/our-process/README.md
structure/where-can-i-find....md

- Update references to "contests" throughout -> "audits(s)", or occasionally "competitions" 
- Add Analysis section to Judging Criteria page
- Update award pool percentages
- Update Sponsors section to better reflect current processes
- Update timeline in the "Our process" section to include pre-sort
- Update Awarding Process page

Add Analysis section; update audit language

---

awarding/fairness-and-validity/README.md
awarding/incentive-model-and-awards/awarding-process.md
roles/certified-contributors/README.md
roles/wardens/README.md

- fixed link to `+backstage role`
- updated metamask link to their newer support url
- fixed Provenance broken links
- fixed OpenZepplin PaymentSplitter broken link

fix broken links

---

roles/wardens/submission-policy.md

Fix bullets

---

awarding/incentive-model-and-awards/README.md

Clarify partial section and add an example

Update partial doc

---

roles/wardens/README.md
roles/wardens/warden-auth.md

Updated the auth/warden related readme docs

Update readme auth

---

awarding/incentive-model-and-awards/README.md
roles/wardens/submission-guidelines.md

- Link "finding" and "report" to submission guidelines for clarity
- Specify _unique_ findings 
- Format submission guidelines for better doc structure

Cloud tweaks

---

awarding/incentive-model-and-awards/README.md

Add details to awarding rules

---

roles/wardens/submission-policy.md

submission policy cleanup

---

awarding/incentive-model-and-awards/awarding-process.md

clean up tax info

---

SUMMARY.md
awarding/incentive-model-and-awards/README.md
roles/wardens/audit-catalyst.md
roles/wardens/submission-guidelines.md

Add audit catalyst and "live criticals" documentation

---

awarding/judging-criteria/README.md

Also clarifying language of reports vs submissions

Add section on prior audit reports

---

awarding/fairness-and-validity/README.md
awarding/incentive-model-and-awards/README.md
awarding/judging-criteria/README.md
roles/judges/README.md
roles/wardens/submission-guidelines.md

judge guideline clarifications
